alter table "public"."Ingredient" drop constraint "Ingredient_id_key";

alter table "public"."Ingredient" drop constraint "Ingredient_user_id_fkey";

alter table "public"."Ingredient" drop constraint "Ingredient_pkey";

drop index if exists "public"."Ingredient_id_key";

drop index if exists "public"."Ingredient_pkey";

drop table "public"."Ingredient";

create table "public"."InventoryIngredient" (
    "id" bigint not null,
    "user_id" uuid not null,
    "name" text not null default ''::text,
    "quantity" text not null default ''::text,
    "unit_measure" text not null default ''::text
);


alter table "public"."InventoryIngredient" enable row level security;

create table "public"."RecipeIngredient" (
    "id" bigint generated by default as identity not null,
    "recipe_id" integer not null,
    "name" text not null default ''::text,
    "quantity" text not null default ''::text,
    "unit_measure" text not null default ''::text
);


alter table "public"."RecipeIngredient" enable row level security;

alter table "public"."Recipe" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."User" alter column "id" set default gen_random_uuid();

CREATE UNIQUE INDEX "RecipeIngredient_id_key" ON public."RecipeIngredient" USING btree (id);

CREATE UNIQUE INDEX "RecipeIngredient_pkey" ON public."RecipeIngredient" USING btree (id);

CREATE UNIQUE INDEX "Ingredient_id_key" ON public."InventoryIngredient" USING btree (id);

CREATE UNIQUE INDEX "Ingredient_pkey" ON public."InventoryIngredient" USING btree (id);

alter table "public"."InventoryIngredient" add constraint "Ingredient_pkey" PRIMARY KEY using index "Ingredient_pkey";

alter table "public"."RecipeIngredient" add constraint "RecipeIngredient_pkey" PRIMARY KEY using index "RecipeIngredient_pkey";

alter table "public"."InventoryIngredient" add constraint "Ingredient_id_key" UNIQUE using index "Ingredient_id_key";

alter table "public"."InventoryIngredient" add constraint "InventoryIngredient_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "User"(id) not valid;

alter table "public"."InventoryIngredient" validate constraint "InventoryIngredient_user_id_fkey";

alter table "public"."RecipeIngredient" add constraint "RecipeIngredient_id_key" UNIQUE using index "RecipeIngredient_id_key";

alter table "public"."RecipeIngredient" add constraint "RecipeIngredient_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES "Recipe"(id) not valid;

alter table "public"."RecipeIngredient" validate constraint "RecipeIngredient_recipe_id_fkey";


