alter table "public"."Recipe" alter column "id" add generated by default as identity;

alter table "public"."Recipe" alter column "id" set data type integer using "id"::integer;

alter table "public"."Recipe" alter column "title" set default '''Sem Título''::text'::text;


